Repository UCSolarCarTeam/Epsilon-Hermes, pull requests merged in 2018-05, with the labels that each got.

#39 Bill/output serial port
  CommunicationLayer/CommDeviceControl/OutputRadioCommDevice.cpp
  CommunicationLayer/CommDeviceControl/OutputRadioCommDevice.h
  CommunicationLayer/CommunicationContainer.cpp
  CommunicationLayer/CommunicationContainer.h
  CommunicationLayer/CommunicationLayer.pro
  InfrastructureLayer/Settings/I_Settings.h
  InfrastructureLayer/Settings/Settings.cpp
  InfrastructureLayer/Settings/Settings.h
  Tests/InfrastructureLayer/Settings/MockSettings.h
  Tests/InfrastructureLayer/Settings/SettingsTest.cpp
  Tests/testconfig.ini
  config.ini.example
Labels: Approved

#44 Safa/epsilon hermes/conversions
  DataLayer/BatteryData/BatteryData.cpp
  DataLayer/DriverControlsData/DriverControlsData.cpp
  DataLayer/MpptData/MpptUnit.cpp
Labels: Awaiting Changes

#42 renamed/updated config to connect to local host
  config.ini.example
Labels: Awaiting Changes

#46 Justin unit conversions
  DataLayer/KeyMotorData/KeyMotorData.cpp
Labels: Awaiting Review
